-- Create stories table
CREATE TABLE public.stories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story text NOT NULL,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  school character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  grades character varying,
  role text,
  ai_usage text
);

-- Add indexes for common queries
CREATE INDEX stories_created_at_idx ON public.stories (created_at DESC);
CREATE INDEX stories_school_idx ON public.stories (school) WHERE school IS NOT NULL;

-- Enable Row Level Security
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public inserts (for story submissions)
CREATE POLICY "Allow public story submissions" ON public.stories
  FOR INSERT
  WITH CHECK (true);

-- Create policy to allow authenticated users to read all stories
CREATE POLICY "Allow authenticated users to read stories" ON public.stories
  FOR SELECT
  USING (auth.role() = 'authenticated');
