-- Create interviews table
CREATE TABLE public.interviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id bigint REFERENCES public.stories(id) ON DELETE SET NULL,
  cal_booking_id character varying NOT NULL UNIQUE,
  cal_booking_uid character varying,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  attendee_name character varying NOT NULL,
  attendee_email character varying NOT NULL,
  attendee_phone character varying,
  status character varying DEFAULT 'scheduled',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb
);

-- Add indexes for common queries
CREATE INDEX interviews_story_id_idx ON public.interviews (story_id) WHERE story_id IS NOT NULL;
CREATE INDEX interviews_cal_booking_id_idx ON public.interviews (cal_booking_id);
CREATE INDEX interviews_start_time_idx ON public.interviews (start_time DESC);
CREATE INDEX interviews_attendee_email_idx ON public.interviews (attendee_email);
CREATE INDEX interviews_status_idx ON public.interviews (status);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_interviews_updated_at
  BEFORE UPDATE ON public.interviews
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Enable Row Level Security
ALTER TABLE public.interviews ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public inserts (for interview bookings)
CREATE POLICY "Allow public interview bookings" ON public.interviews
  FOR INSERT
  WITH CHECK (true);

-- Create policy to allow authenticated users to read all interviews
CREATE POLICY "Allow authenticated users to read interviews" ON public.interviews
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create policy to allow authenticated users to update interview status
CREATE POLICY "Allow authenticated users to update interviews" ON public.interviews
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Add comment explaining the status values
COMMENT ON COLUMN public.interviews.status IS 'Possible values: scheduled, confirmed, cancelled, completed, no_show, rescheduled';

-- Add comment explaining the metadata column
COMMENT ON COLUMN public.interviews.metadata IS 'Stores additional Cal.com booking data and custom fields in JSON format';
